[build]
builder = "NIXPACKS"

[deploy]
startCommand = "astro preview --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
